In [1]:
import pandas as pd

stock_names = [
    "Samsung",
    "SKHynix",
    "DosanEner",
    "Kodex200"
]

df = pd.read_csv("../data/Samsung_stock.csv", index_col=0)
daily_return = df["Close"].pct_change()

daily_return.head()

2026-04-03         NaN
2026-04-06    0.037057
2026-04-07    0.017607
2026-04-08    0.071247
2026-04-09   -0.030879
Name: Close, dtype: float64

In [2]:
average_return = daily_return.mean()
print(f"평균: {average_return * 100:.2f}%")

평균: 0.97%

In [3]:
volatility = daily_return.std()
print(f"변동성: {volatility * 100:.2f}%")

변동성: 5.22%

In [4]:
results = []

for name in stock_names:
    df = pd.read_csv(f"../data/{name}_stock.csv", index_col=0)

    daily_return = df["Close"].pct_change()

    average_return = daily_return.mean() * 100
    volatility = daily_return.std() * 100

    results.append([
        name,
        average_return,
        volatility
    ])

result_df = pd.DataFrame(
    results,
    columns=["Stock", "Average Return (%)", "Volatility (%)"]
)

result_df

       Stock  Average Return (%)  Volatility (%)
0    Samsung            0.970348        5.221283
1    SKHynix            1.871030        6.187025
2  DosanEner           -0.105681        4.060231
3   Kodex200                 NaN             NaN

In [5]:
result_df["Risk Adjusted Return"] = (
    result_df["Average Return (%)"] /
    result_df["Volatility (%)"]
)

result_df

       Stock  Average Return (%)  Volatility (%)  Risk Adjusted Return
0    Samsung            0.970348        5.221283              0.185845
1    SKHynix            1.871030        6.187025              0.302412
2  DosanEner           -0.105681        4.060231             -0.026028
3   Kodex200                 NaN             NaN                   NaN

In [6]:
result_df = result_df.sort_values(
    by="Risk Adjusted Return",
    ascending=False
)
result_df

       Stock  Average Return (%)  Volatility (%)  Risk Adjusted Return
1    SKHynix            1.871030        6.187025              0.302412
0    Samsung            0.970348        5.221283              0.185845
2  DosanEner           -0.105681        4.060231             -0.026028
3   Kodex200                 NaN             NaN                   NaN

In [7]:
result_df.iloc[0]

Stock                    SKHynix
Average Return (%)       1.87103
Volatility (%)          6.187025
Risk Adjusted Return    0.302412
Name: 1, dtype: object