In [14]:
import pandas as pd

stock_names = [
    "Samsung",
    "SKHynix",
    "DosanEner",
    "Kodex200"
]

df = pd.read_csv("../data/Samsung_stock.csv", index_col=0)
daily_return = df["Close"].pct_change()

daily_return.head()

2026-03-26         NaN
2026-03-27    0.000000
2026-03-30   -0.019073
2026-03-31   -0.051617
2026-04-01    0.134270
Name: Close, dtype: float64

In [15]:
average_return = daily_return.mean()
print(f"평균: {average_return * 100:.2f}%")

평균: 1.17%

In [16]:
volatility = daily_return.std()
print(f"변동성: {volatility * 100:.2f}%")

변동성: 5.20%

In [22]:
results = []

for name in stock_names:
    df = pd.read_csv(f"../data/{name}_stock.csv", index_col=0)

    daily_return = df["Close"].pct_change()

    average_return = daily_return.mean() * 100
    volatility = daily_return.std() * 100

    results.append([
        name,
        average_return,
        volatility
    ])

result_df = pd.DataFrame(
    results,
    columns=["Stock", "Average Return (%)", "Volatility (%)"]
)

result_df

       Stock  Average Return (%)  Volatility (%)
0    Samsung            1.170097        5.200770
1    SKHynix            1.946082        5.997512
2  DosanEner           -0.228863        4.129484
3   Kodex200            0.954036        3.957866

In [23]:
result_df["Risk Adjusted Return"] = (
    result_df["Average Return (%)"] /
    result_df["Volatility (%)"]
)

result_df

       Stock  Average Return (%)  Volatility (%)  Risk Adjusted Return
0    Samsung            1.170097        5.200770              0.224985
1    SKHynix            1.946082        5.997512              0.324482
2  DosanEner           -0.228863        4.129484             -0.055422
3   Kodex200            0.954036        3.957866              0.241048