In [26]:
import pandas as pd

stock_names = [
    "Samsung",
    "SKHynix",
    "DosanEner",
    "Kodex200"
]

df = pd.read_csv(
    "../data/Samsung_stock.csv",
    index_col = 0
)

close_df = df[["Close"]]

close_df.head()

               Close
2026-04-03  186200.0
2026-04-06  193100.0
2026-04-07  196500.0
2026-04-08  210500.0
2026-04-09  204000.0

In [27]:
close_df = close_df.rename(
    columns={
        "Close":"Samsung"
    }
)

close_df.head()

             Samsung
2026-04-03  186200.0
2026-04-06  193100.0
2026-04-07  196500.0
2026-04-08  210500.0
2026-04-09  204000.0

In [28]:
stock_data = {}

for name in stock_names:
    df = pd.read_csv(
        f"../data/{name}_stock.csv",
        index_col=0
    )

    close_df = df[["Close"]]

    close_df = close_df.rename(
        columns={
            "Close":name
        }
    )

    stock_data[name] = close_df
    print(stock_data.keys())

dict_keys(['Samsung'])
dict_keys(['Samsung', 'SKHynix'])
dict_keys(['Samsung', 'SKHynix', 'DosanEner'])
dict_keys(['Samsung', 'SKHynix', 'DosanEner', 'Kodex200'])

In [29]:
stock_data["Samsung"].head()

             Samsung
2026-04-03  186200.0
2026-04-06  193100.0
2026-04-07  196500.0
2026-04-08  210500.0
2026-04-09  204000.0

In [30]:
merged_df = pd.concat(
    stock_data.values(),
    axis=1
)

merged_df.head()

             Samsung       SKHynix  DosanEner  Kodex200
2026-04-03  186200.0  8.758536e+05    96600.0       NaN
2026-04-06  193100.0  8.858519e+05    95700.0       NaN
2026-04-07  196500.0  9.158469e+05    94900.0       NaN
2026-04-08  210500.0  1.032827e+06   101200.0       NaN
2026-04-09  204000.0  9.978331e+05   100000.0       NaN

In [31]:
merged_df.to_csv("../data/merged_stock_data.csv")
print("저장 완료!")

저장 완료!