In [16]:
def hello():
    print("안녕하세요")

In [17]:
hello()

안녕하세요

In [18]:
def hello(name):
    print("안녕하세요", name)

In [19]:
hello("학진")

안녕하세요 학진

In [20]:
def get_news(query):
    print(query)

get_news("삼성전자")
get_news("SK하이닉스")

삼성전자
SK하이닉스

In [21]:
def get_news(query):
    news_list = []

In [24]:
import pandas as pd
import sys
import os

sys.path.append(os.path.abspath(".."))
from src.news import get_news
from src.config import NEWS_QUERIES

all_news = []

for query in NEWS_QUERIES.values():
    all_news.extend(get_news(query))

news_df = pd.DataFrame(all_news)

news_df.head()

,종목,제목,링크,요약,날짜
0,삼성전자,"코웨이, 아이콘 얼음정수기 5종 풀라인업으로 소비자 맞춤 공략...6월 신...",http://www.consumernews.co.kr/news/articleView...,삼성전자와 LG전자까지 뛰어들며 경쟁이 심화된 상황에서 코웨이는 5종 풀라인업을 앞...,"Wed, 15 Jul 2026 15:44:00 +0900"
1,삼성전자,"신한자산운용, 'SOL AI반도체TOP2플러스 ETF' 종목 조정",https://www.thereport.co.kr/news/articleView.h...,"리밸런싱 이후 주요 편입 비중은 SK하이닉스 25.75%, 삼성전자 24.84%, ...","Wed, 15 Jul 2026 15:44:00 +0900"
2,삼성전자,"정부 ‘하이퍼 AI 네트워크’ 구축 시동…SKT·KT, 실증 나선다",https://www.ekn.kr/web/view.php?key=2026071502...,"이번 사업에는 삼성전자, 에릭슨, 노키아, 에치에프알(HFR) 등 4개 제조사의 A...","Wed, 15 Jul 2026 15:44:00 +0900"
3,삼성전자,충남도 '202조 원 첨단산업 투자' 속도 높인다,https://www.ccdn.co.kr/news/articleView.html?i...,"도는 15일 도청에서 삼성전자, 삼성디스플레이, 삼성에스디아이(SDI), 에스케이텔...","Wed, 15 Jul 2026 15:43:00 +0900"
4,삼성전자,"""하루라도 앞당겨라"" 반도체 인허가 드라이버 건 추미애",https://n.news.naver.com/mnews/article/018/000...,추미애 경기도지사가 삼성전자의 평택캠퍼스(P5 FAB2) 건설을 위한 고덕산업단지 ...,"Wed, 15 Jul 2026 15:43:00 +0900"

In [ ]:
stock_queries = [
    "삼성전자",
    "SK하이닉스",
    "두산에너빌리티",
    "KODEX200"
]

all_news = []

for query in stock_queries:
    news_list = get_news(query)

    all_news.extend(news_list)

news_df = pd.DataFrame(all_news)

news_df.head()

,종목,제목,링크,요약,날짜
0,삼성전자,"""스마트폰 다음은 글라스""… 삼성, '항상 연결된 AI' 구축",https://www.mediapen.com/news/view/1110338,삼성전자가 첫 AI 글라스 공개를 앞두고 갤럭시 AI 생태계 확장에 속도를 내고 있...,"Wed, 15 Jul 2026 15:26:00 +0900"
1,삼성전자,"삼성전자, 폴더블 혁신 집약체 ‘플렉스 티타늄’ 기술 공개",http://journal.kobeta.com/?post_type=post&p=63307,제공: 삼성전자 삼성전자가 7월 15일 차세대 갤럭시 폴더블 기기에 적용될 ‘플렉스...,"Wed, 15 Jul 2026 15:26:00 +0900"
2,삼성전자,"삼성전자, 차세대 디스플레이 기술 ‘플렉스 티타늄’ 공개… 주름 줄이...",https://www.mediawatch.kr/news/article.html?no...,인싸잇=이서호 기자 | 삼성전자가 차세대 갤럭시 폴더블 제품에 적용될 새로운 디스플...,"Wed, 15 Jul 2026 15:24:00 +0900"
3,삼성전자,"반도체 초과 이익 논란, 산업부장관 “성과급 대신 재투자 필요”",https://www.mediawatch.kr/news/article.html?no...,산업부는 삼성전자 노사 간 임금 협상에서 언급된 ‘영업이익 N%’ 성과급 논란을 계...,"Wed, 15 Jul 2026 15:24:00 +0900"
4,삼성전자,"李대통령 ""삼전·닉스 레버리지 ETF 때문에 많이 당하신 듯"" 보완책 마련...",https://n.news.naver.com/mnews/article/123/000...,이재명 대통령이 최근 증시 변동성 확대의 원인으로 지목된 삼성전자·SK하이닉스 단일...,"Wed, 15 Jul 2026 15:24:00 +0900"

In [ ]:
news_df.head()

,종목,제목,링크,요약,날짜
0,삼성전자,"""스마트폰 다음은 글라스""… 삼성, '항상 연결된 AI' 구축",https://www.mediapen.com/news/view/1110338,삼성전자가 첫 AI 글라스 공개를 앞두고 갤럭시 AI 생태계 확장에 속도를 내고 있...,"Wed, 15 Jul 2026 15:26:00 +0900"
1,삼성전자,"삼성전자, 폴더블 혁신 집약체 ‘플렉스 티타늄’ 기술 공개",http://journal.kobeta.com/?post_type=post&p=63307,제공: 삼성전자 삼성전자가 7월 15일 차세대 갤럭시 폴더블 기기에 적용될 ‘플렉스...,"Wed, 15 Jul 2026 15:26:00 +0900"
2,삼성전자,"삼성전자, 차세대 디스플레이 기술 ‘플렉스 티타늄’ 공개… 주름 줄이...",https://www.mediawatch.kr/news/article.html?no...,인싸잇=이서호 기자 | 삼성전자가 차세대 갤럭시 폴더블 제품에 적용될 새로운 디스플...,"Wed, 15 Jul 2026 15:24:00 +0900"
3,삼성전자,"반도체 초과 이익 논란, 산업부장관 “성과급 대신 재투자 필요”",https://www.mediawatch.kr/news/article.html?no...,산업부는 삼성전자 노사 간 임금 협상에서 언급된 ‘영업이익 N%’ 성과급 논란을 계...,"Wed, 15 Jul 2026 15:24:00 +0900"
4,삼성전자,"李대통령 ""삼전·닉스 레버리지 ETF 때문에 많이 당하신 듯"" 보완책 마련...",https://n.news.naver.com/mnews/article/123/000...,이재명 대통령이 최근 증시 변동성 확대의 원인으로 지목된 삼성전자·SK하이닉스 단일...,"Wed, 15 Jul 2026 15:24:00 +0900"

In [ ]:
news_df.to_csv(
    "../data/news_dataset.csv",
    index=False
)

print("저장 완료!")

저장 완료!